mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/taotao
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    timeout: 5000
# redis-single
    host: localhost
    port: 6379
# redis-cluster
#    cluster:
#      max-redirects: 3
#      nodes:
#      - 192.168.223.128:6380
#      - 192.168.223.128:6381
#      - 192.168.223.128:6382
#    lettuce:
#      pool:
#        max-active: 100
#        max-idle: 100
#        min-idle: 50
#        max-wait: 6000

dubbo:
  application:
    name: e3-content
  registry:
    address: zookeeper://localhost:2181
  scan:
    basePackages: com.taotao.content.service
  protocol:
    port: 20881