mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/taotao
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    timeout: 5000
# redis-single
    host: localhost
    port: 6379

dubbo:
  application:
    name: e3-order
  registry:
    address: zookeeper://localhost:2181
  scan:
    basePackages: com.taotao.order.service
  protocol:
    port: 20885